language: elixir
elixir: 1.7.4
otp_release: '19.0'
script:
- npm install -g npx
- mix format --check-formatted
- mix test
- cd assets && npm install && npx elm-format --validate elm && npx webpack --mode
  production
- cd .. && MIX_ENV=prod mix phx.digest
- MIX_ENV=prod mix release
deploy:
  provider: releases
  api_key:
    secure: MRU7c9JJIx8f/JQynPwUKVgjUZm2Oy2sEuq1eceoEOcEs1WywzVfv90MvBZWLYEyPRQG2T4C6z64Z20uIFQ6n+qXv7LOjor4d2oMkNi4Pt9bZsbbDda+E+TPeamtDDB0PzGG5Quk88S3HImz6MbTyO3ha1MO8PFwcD9MmLNr6HRMH3p9xOmPl6uKoQMxU58vOpN14UTv0vTsJC77Pe/gYKFY07SwkSVwYdn5xn8DXIupaHh7UKLi2kmrFi4PswfKgaRr0mPMUsk74DxFrEaNaeoFKEvC554IzHoQEVT3FBul68vwn3EQn/s7i2pJmeGYdqNXv+URD6TzOpsGUXi2qrdE2k0TOpEwx1EZR8lJSxvBLOKxF7ofbAjJTbE4GCFsK8may7Dh7uAKm51tR9hzs5u4B7tKGD0j4HQQ5tkY3S8NZbxASYC3YC5hv0fPQtUeyem90dG2U98J9zDtcGAaagpSXg69V2TkyiqDIQRD6/p15/RqIsqQKrgbeWpYueZwlucAXDrunoWJWyjghDKD49BrewQ9ETaBrUu/3u3xywbJt/E2c7pRjqmi7ouqwxJBejQRwyRIZtC/MdFWLfad1W30OfbtwSr/hyZcucuqPuO/QGt7ME06WzwmietLeMsNyU3I9lYDnQPOjvW2AhUCXr94vKA9YdiWmhmrzS6FKic=
  file: _build/prod/rel/glare/bin/glare
  on:
    repo: dottorblaster/glare
    tags: true
