language: elixir
elixir: '1.7.4'
otp_release: '19.0'

jobs:
  include:
    - stage: "Check Elixir code format"
      script: mix format --check-formatted
    - stage: "Run tests"
      script: mix test
    - stage: "Check Elm code format"
      script: cd assets && npm install && npx elm-format 
